version: "3.8"
services:
  lucree-challenge:
    image: acim/go-reflex
    environment:
      - RACE_DETECTOR=1
      - BUILD_ARGS=./cmd/api/main.go
    container_name: lucree-challenge
    ports:
      - 9191:9191
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    image: postgres:14.7
    restart: always
    environment:
      - POSTGRES_USER=lucree-challenge
      - POSTGRES_PASSWORD=lucree-challenge-pass
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://lucree-challenge:lucree-challenge-pass@postgres:5432/lucree-challenge?sslmode=disable", "up"]
    depends_on:
      - postgres

volumes:
  postgres-data:
