# Generated by Django 3.2.9 on 2021-12-12 19:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('pan', models.CharField(max_length=16)),
                ('expiry_mm', models.CharField(max_length=2)),
                ('expiry_yyyy', models.CharField(max_length=4)),
                ('security_code', models.CharField(default=1234, max_length=4)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_account_api.account')),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('friendship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend', to='digital_account_api.account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='digital_account_api.account')),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('transfer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_message', models.CharField(max_length=100)),
                ('total_to_pay', models.IntegerField()),
                ('billing_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_account_api.card')),
                ('friendship_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='digital_account_api.friend')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_account_api.account')),
            ],
        ),
    ]
