# Generated by Django 3.2.9 on 2021-12-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_account_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='friendship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_account_api.friend'),
        ),
    ]
