# Generated by Django 4.2.1 on 2023-05-11 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="birthday",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 5, 11, 13, 21, 12, 412387, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
