# Generated by Django 4.2.1 on 2023-05-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        ("clients", "0003_alter_client_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_to_transfer", models.IntegerField(default=0)),
                (
                    "billing_card",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.clientcard",
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
