# Generated by Django 4.2.1 on 2023-05-11 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfer",
            old_name="total_to_transfer",
            new_name="total_to_pay",
        ),
    ]
