# Generated by Django 4.2.1 on 2023-05-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0002_alter_client_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "card_id",
                    models.CharField(max_length=90, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(default="", max_length=60)),
                ("pan", models.CharField(default="", max_length=16, unique=True)),
                ("expiry_mm", models.CharField(default="", max_length=2)),
                ("expiry_yyyy", models.CharField(default="", max_length=4)),
                ("security_code", models.CharField(default="", max_length=4)),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.card",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
