# Generated by Django 4.2.1 on 2023-05-11 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0001_initial"),
        ("clients", "0004_alter_client_birthday"),
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientCard",
            new_name="BillingCard",
        ),
    ]
